{% set name = "eval-type-backport" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz"
  sha256: f0576b4cf01ebb5bd358d02314d31846af5e07678387486e2c798af0e7d849c1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - python

test:
  imports:
    - eval_type_backport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alexmojaki/eval_type_backport/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Like `typing._eval_type`, but lets older Python versions use newer typing features.
  description:  |
    This is a tiny package providing a replacement for typing._eval_type to support newer typing features in older Python versions.
  doc_url: https://github.com/alexmojaki/eval_type_backport/
  dev_url: https://github.com/alexmojaki/eval_type_backport/

extra:
  recipe-maintainers:
    - solesnake
